version: '3'

services:
    db1:
        build: ./docker-postgresql
        container_name: db1
        volumes:
            - ./db1-schema:/docker-entrypoint-initdb.d/
        environment:
            - POSTGRES_DB=db
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
        ports:
            - 5434:5432

    db2:
        build: ./docker-postgresql
        container_name: db2
        volumes:
            - ./db2-schema:/docker-entrypoint-initdb.d/
        environment:
            - POSTGRES_DB=db
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
        ports:
            - 5433:5432

    proxydb:
        build: ./docker-postgresql
        container_name: proxydb
        volumes:
            - ./proxy-db-schema:/docker-entrypoint-initdb.d/
        environment:
            - POSTGRES_DB=db
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
        ports:
            - 5432:5432

    dwhdb:
        build: ./docker-postgresql
        container_name: dwhdb
        volumes:
            - ./dwh-db-schema:/docker-entrypoint-initdb.d/
        environment:
            - POSTGRES_DB=db
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
        ports:
            - 5431:5432
