version: '3'

services:
    db1:
        image: postgres:latest
        container_name: db1
        volumes:
            - ./db1-schema:/docker-entrypoint-initdb.d/
        environment:
            - POSTGRES_DB=db
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
        ports:
            - 5434:5432

    db2:
        image: postgres:latest
        container_name: db2
        volumes:
            - ./db2-schema:/docker-entrypoint-initdb.d/
        environment:
            - POSTGRES_DB=db
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
        ports:
            - 5433:5432

    proxydb:
        image: postgres:latest
        container_name: proxydb
        volumes:
            - ./proxy-db:/docker-entrypoint-initdb.d/
        environment:
            - POSTGRES_DB=db
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
        ports:
            - 5432:5432
